"use client";
import {useMemo,useState} from "react";import data from "./products.json";
type P={fornecedor:string;codigo:string;descricao:string;categoria:string;unidade:string;pcs_caixa:number|null;preco_unitario:number|null;pagina:number;status_revisao:string;imagem:string;descricao_detalhada?:string;caracteristicas?:string[];fonte?:string;fonte_nome?:string};const products=data as P[];const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
export default function Home(){const[q,setQ]=useState("");const[status,setStatus]=useState("todos");const[page,setPage]=useState(1);const[markup,setMarkup]=useState(60);const[selected,setSelected]=useState<P|null>(null);const filtered=useMemo(()=>{const n=q.trim().toLocaleLowerCase("pt-BR");return products.filter(p=>(!n||`${p.codigo} ${p.descricao} ${p.categoria}`.toLocaleLowerCase("pt-BR").includes(n))&&(status==="todos"||(status==="revisar"?p.status_revisao==="Revisar":p.status_revisao!=="Revisar")))},[q,status]);const pages=Math.max(1,Math.ceil(filtered.length/30)),safe=Math.min(page,pages),visible=filtered.slice((safe-1)*30,safe*30),price=(p:P)=>p.preco_unitario==null?null:p.preco_unitario*(1+markup/100);return <main>
<header className="topbar"><div className="brand"><span className="brandMark">C</span><div><strong>COLI Distribuidora</strong><small>Inteligência de preços para licitações</small></div></div><div className="catalogMeta"><span>Catálogo atual</span><strong>Lehmox · 15/07/2026</strong></div></header>
<section className="hero"><div><p className="eyebrow">CATÁLOGO PROFISSIONAL DE FORNECEDORES</p><h1>Produtos, preços e informações<br/>em um só lugar.</h1><p className="subtitle">Consulte imagens, descrições, dados técnicos disponíveis e o preço sugerido com sua margem comercial.</p></div><div className="logoPanel"><img src="/coli-logo.png" alt="COLI Distribuidora Ltda"/></div></section>
<section className="controls"><label className="searchBox"><span>Buscar produto</span><input value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="Nome, categoria ou código"/></label><label><span>Situação</span><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="todos">Todos os produtos</option><option value="prontos">Dados identificados</option><option value="revisar">Requer conferência</option></select></label><label><span>Margem</span><div className="markupInput"><input type="number" min="0" max="500" value={markup} onChange={e=>setMarkup(Number(e.target.value))}/><b>%</b></div></label></section>
<section className="summary"><div><strong>{products.length}</strong><span>produtos</span></div><div><strong>{products.filter(p=>p.fonte).length}</strong><span>fichas pesquisadas</span></div><div><strong>{filtered.length}</strong><span>resultados</span></div><p>Preço sugerido = custo + {markup}%</p></section>
{visible.length?<section className="grid">{visible.map(p=><button className="card" key={`${p.pagina}-${p.codigo}`} onClick={()=>setSelected(p)}><div className="imageWrap"><img src={p.imagem} alt={p.descricao||p.codigo} loading="lazy"/>{p.fonte&&<span className="verified">Fonte verificada</span>}</div><div className="cardBody"><div className="codeRow"><span>{p.codigo}</span><small>Pág. {p.pagina}</small></div><h2>{p.descricao||"Descrição pendente"}</h2><p className="miniDesc">{p.descricao_detalhada}</p><div className="details"><span>Un.: {p.unidade}</span><span>Caixa: {p.pcs_caixa??"—"}</span></div><div className="prices"><div><small>Custo</small><strong>{p.preco_unitario==null?"A revisar":money.format(p.preco_unitario)}</strong></div><div className="suggested"><small>Com margem</small><strong>{price(p)==null?"—":money.format(price(p)!)}</strong></div></div><span className="more">Ver ficha completa →</span></div></button>)}</section>:<div className="empty">Nenhum produto encontrado.</div>}
<nav className="pagination"><button disabled={safe===1} onClick={()=>setPage(v=>Math.max(1,v-1))}>Anterior</button><span>Página <strong>{safe}</strong> de {pages}</span><button disabled={safe===pages} onClick={()=>setPage(v=>Math.min(pages,v+1))}>Próxima</button></nav><footer>COLI Distribuidora Ltda · Confirme disponibilidade, compatibilidade e condições com o fornecedor antes da proposta.</footer>
{selected&&<div className="modalBackdrop" onMouseDown={()=>setSelected(null)}><section className="modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><div className="modalImage"><img src={selected.imagem} alt={selected.descricao}/></div><div className="modalContent"><p className="eyebrow">{selected.codigo} · LEHMOX</p><h2>{selected.descricao||"Produto em conferência"}</h2><p className="fullDesc">{selected.descricao_detalhada}</p><h3>Informações disponíveis</h3><ul>{selected.caracteristicas?.map(x=><li key={x}>{x}</li>)}</ul><div className="modalPrices"><div><small>Custo unitário</small><strong>{selected.preco_unitario==null?"A revisar":money.format(selected.preco_unitario)}</strong></div><div><small>Preço com {markup}%</small><strong>{price(selected)==null?"—":money.format(price(selected)!)}</strong></div></div>{selected.fonte?<a className="source" href={selected.fonte} target="_blank" rel="noreferrer">Consultar fonte: {selected.fonte_nome||"especificações"} ↗</a>:<p className="sourceNote">Dados baseados no catálogo do fornecedor. Especificações externas ainda não foram localizadas com segurança.</p>}</div></section></div>}</main>}
