"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import "./licitacoes.css";

type Item = { id:number; item_numero:string; descricao_edital:string; quantidade:number; unidade:string; produto_codigo:string; produto_nome:string; marca:string; modelo:string; fornecedor:string; link_compra:string; custo_unitario:number; valor_inicial:number; valor_minimo:number; justificativa:string; status_compra:string };
type Licitacao = { id:number; numero:string; orgao:string; portal:string; objeto:string; cidade:string; uf:string; data_disputa:string; status:string; link_licitei:string; observacoes:string; items:Item[] };
const money = new Intl.NumberFormat("pt-BR", { style:"currency", currency:"BRL" });

export default function LicitacoesPage() {
  const [licitacoes,setLicitacoes]=useState<Licitacao[]>([]),[selected,setSelected]=useState<number|null>(null),[loading,setLoading]=useState(true),[showNew,setShowNew]=useState(false),[showItem,setShowItem]=useState(false);
  const load=()=>fetch("/api/licitacoes").then(r=>r.json()).then(body=>{setLicitacoes(body.licitacoes||[]);setSelected(current=>current??body.licitacoes?.[0]?.id??null)}).finally(()=>setLoading(false));
  useEffect(()=>{load()},[]);
  const active=licitacoes.find(l=>l.id===selected)||null;
  const totals=useMemo(()=>active?.items.reduce((acc,item)=>({custo:acc.custo+item.custo_unitario*item.quantidade,minimo:acc.minimo+item.valor_minimo*item.quantidade,inicial:acc.inicial+item.valor_inicial*item.quantidade}),{custo:0,minimo:0,inicial:0})||{custo:0,minimo:0,inicial:0},[active]);
  async function createLicitacao(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));await fetch("/api/licitacoes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});setShowNew(false);await load()}
  async function createItem(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!active)return;const data=Object.fromEntries(new FormData(e.currentTarget));await fetch(`/api/licitacoes/${active.id}/items`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});setShowItem(false);await load()}
  return <main className="tenderApp">
    <header className="appHeader"><a className="brand" href="/"><span>C</span><div><b>COLI Distribuidora</b><small>Gestão de licitações</small></div></a><nav><a href="/">Catálogo</a><a className="active" href="/licitacoes">Licitações</a><a href="/logout">Sair</a></nav></header>
    <section className="titleRow"><div><p>PAINEL COMERCIAL PRIVADO</p><h1>Licitações e carrinhos de compra</h1><span>Acompanhe cada proposta, produto escolhido e local de compra.</span></div><button onClick={()=>setShowNew(true)}>+ Nova licitação</button></section>
    <section className="metrics"><article><small>Licitações</small><strong>{licitacoes.length}</strong></article><article><small>Em andamento</small><strong>{licitacoes.filter(l=>!['Perdida','Concluída'].includes(l.status)).length}</strong></article><article><small>Itens planejados</small><strong>{licitacoes.reduce((n,l)=>n+l.items.length,0)}</strong></article><article><small>Compras estimadas</small><strong>{money.format(licitacoes.flatMap(l=>l.items).reduce((n,i)=>n+i.custo_unitario*i.quantidade,0))}</strong></article></section>
    {loading?<div className="empty">Carregando licitações...</div>:!licitacoes.length?<div className="empty"><b>Nenhuma licitação cadastrada ainda.</b><span>As licitações trabalhadas serão organizadas aqui com seus respectivos carrinhos.</span><button onClick={()=>setShowNew(true)}>Cadastrar primeira licitação</button></div>:<section className="workspace"><aside><h2>Licitações</h2>{licitacoes.map(l=><button key={l.id} className={selected===l.id?'selected':''} onClick={()=>setSelected(l.id)}><span>{l.numero}</span><b>{l.orgao}</b><small>{l.data_disputa||'Data não informada'} · {l.status}</small></button>)}</aside>{active&&<div className="detail"><div className="tenderHead"><div><p>{active.portal} · {active.numero}</p><h2>{active.orgao}</h2><span>{active.cidade}{active.uf?`/${active.uf}`:''}</span></div><span className="status">{active.status}</span></div><div className="object"><small>Objeto da licitação</small><p>{active.objeto}</p>{active.link_licitei&&<a href={active.link_licitei} target="_blank">Abrir no Licitei ↗</a>}</div><div className="cartHead"><div><h3>Carrinho desta licitação</h3><span>{active.items.length} itens precificados</span></div><button onClick={()=>setShowItem(true)}>+ Adicionar item</button></div>{!active.items.length?<div className="noItems">Nenhum produto selecionado para esta licitação.</div>:<div className="cart">{active.items.map(item=><article key={item.id}><div className="itemNo">{item.item_numero}</div><div className="itemMain"><small>EXIGÊNCIA DO EDITAL</small><p>{item.descricao_edital}</p><h4>{item.produto_nome}</h4><div className="tags"><span>{item.marca||'Marca a revisar'}</span><span>{item.modelo||'Modelo a revisar'}</span><span>{item.fornecedor||'Fornecedor a revisar'}</span></div>{item.justificativa&&<details><summary>Por que este produto atende?</summary><p>{item.justificativa}</p></details>}{item.link_compra&&<a href={item.link_compra} target="_blank">Comprar com o fornecedor ↗</a>}</div><div className="itemPrice"><small>{item.quantidade} {item.unidade}</small><span>Custo unitário <b>{money.format(item.custo_unitario)}</b></span><span>Valor mínimo <b>{money.format(item.valor_minimo)}</b></span><strong>{money.format(item.custo_unitario*item.quantidade)}</strong></div></article>)}</div>}<div className="totals"><div><small>Custo total do carrinho</small><strong>{money.format(totals.custo)}</strong></div><div><small>Valor mínimo total</small><strong>{money.format(totals.minimo)}</strong></div><div><small>Margem estimada</small><strong>{money.format(totals.minimo-totals.custo)}</strong></div></div></div>}</section>}
    {showNew&&<div className="modalBack"><form className="modalForm" onSubmit={createLicitacao}><button type="button" className="close" onClick={()=>setShowNew(false)}>×</button><h2>Nova licitação</h2><div className="formGrid"><label>Número<input name="numero" required/></label><label>Portal<input name="portal" defaultValue="Licitei"/></label><label className="wide">Órgão<input name="orgao" required/></label><label className="wide">Objeto<textarea name="objeto" required/></label><label>Cidade<input name="cidade"/></label><label>UF<input name="uf" maxLength={2}/></label><label>Data da disputa<input name="data_disputa" type="datetime-local"/></label><label>Status<select name="status"><option>Em análise</option><option>Recebendo proposta</option><option>Participando</option><option>Vencida</option><option>Perdida</option><option>Concluída</option></select></label><label className="wide">Link no Licitei<input name="link_licitei" type="url"/></label><label className="wide">Observações<textarea name="observacoes"/></label></div><button className="primary">Salvar licitação</button></form></div>}
    {showItem&&active&&<div className="modalBack"><form className="modalForm itemForm" onSubmit={createItem}><button type="button" className="close" onClick={()=>setShowItem(false)}>×</button><h2>Adicionar produto ao carrinho</h2><div className="formGrid"><label>Item do edital<input name="item_numero" required/></label><label>Quantidade<input name="quantidade" type="number" step="0.01" defaultValue="1"/></label><label className="wide">Descrição do edital<textarea name="descricao_edital" required/></label><label className="wide">Produto escolhido<input name="produto_nome" required/></label><label>Código<input name="produto_codigo"/></label><label>Marca<input name="marca"/></label><label>Modelo<input name="modelo"/></label><label>Fornecedor<input name="fornecedor"/></label><label>Custo unitário<input name="custo_unitario" type="number" step="0.01" required/></label><label>Valor inicial<input name="valor_inicial" type="number" step="0.01"/></label><label>Valor mínimo<input name="valor_minimo" type="number" step="0.01" placeholder="Automático: custo + 60%"/></label><label>Unidade<input name="unidade" defaultValue="UN"/></label><label className="wide">Link direto de compra<input name="link_compra" type="url"/></label><label className="wide">Justificativa técnica<textarea name="justificativa" placeholder="Explique como o produto atende ao termo de referência"/></label></div><button className="primary">Adicionar ao carrinho</button></form></div>}
  </main>
}
